import {readWorkbook,dateFromSerial,sourceRows,groupRows} from './xlsx.js';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n),num=n=>new Intl.NumberFormat('de-DE',{maximumFractionDigits:4}).format(n);
let book,teachers=[],groups=[],extras=[],valid=false;
const teacher=()=>teachers.find(t=>String(t.A)===$('teacher').value);
function notify(text,error=false){$('status').textContent=text;$('status').className=error?'error':'';}
$('file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;$('form').disabled=true;valid=false;$('invoice').hidden=true;$('empty').style.display='flex';$('print').disabled=true;notify('Excelを読み込んでいます…');try{if(file.size>20000000)throw Error('20MB以下のExcelを選択してください。');book=await readWorkbook(await file.arrayBuffer());teachers=book['講師一覧'].filter(r=>typeof r.A==='number'&&r.B);if(!teachers.length)throw Error('講師一覧を読み込めませんでした。');const months=[...new Set(book['出勤簿'].filter(r=>typeof r.A==='number'&&r.F).map(r=>dateFromSerial(r.A).toISOString().slice(0,7)))].sort();if(!months.length)throw Error('日付のある勤怠データがありません。');$('teacher').innerHTML=teachers.map(t=>`<option value="${esc(t.A)}">${esc(t.C)} ${esc(t.B)}</option>`).join('');$('month').innerHTML=months.map(m=>`<option value="${m}">${m.replace('-','年')}月</option>`).join('');$('month').value=months.at(-1);$('filename').textContent=file.name;$('form').disabled=false;reload();}catch(e){notify(e.message,true);}});
function reload(){valid=false;extras=[];drawExtras();$('confirmed').checked=false;try{const t=teacher(),month=$('month').value;groups=groupRows(sourceRows(book,t.B,month));const [y,m]=month.split('-').map(Number);$('date').value=new Date(Date.UTC(y,m,0)).toISOString().slice(0,10);$('number').value=`${y}-${String(m).padStart(2,'0')}-${t.A}`;valid=true;notify(`${teachers.length}名の講師を読み込みました。金額はExcelに保存された値を使用します。数式の再計算は行いません。`);$('categories').innerHTML=groups.length?groups.map((g,i)=>`<label class="category"><input type="checkbox" data-group="${i}" checked><span>${esc(g.name)}<br><small>${num(g.qty)} × ${money(g.unit)}</small></span><b>${money(g.amount)}</b></label>`).join(''):'<p class="hint">この月の勤怠はありません。追加明細を入力できます。</p>';$('categories').querySelectorAll('input').forEach(c=>c.onchange=()=>{groups[Number(c.dataset.group)].enabled=c.checked;changed();});render();}catch(e){$('categories').textContent='明細を読み込めません。';$('invoice').hidden=true;$('empty').style.display='flex';$('print').disabled=true;notify(e.message,true);}}
function changed(){$('confirmed').checked=false;render();}
$('teacher').onchange=reload;$('month').onchange=reload;$('date').oninput=changed;$('number').oninput=changed;
function extraOptions(){return [...new Map((book?.['index_sheet']??[]).filter(r=>r.I&&r.I!=='Kategorie').map(r=>[String(r.I),r])).values()];}
function extraRate(option){const t=teacher();const col={Unterricht:'M',Pausenaufsicht:'N',Fahrgeld:'O'}[option.I];const value=col?t?.[col]:option.M;return typeof value==='number'&&Number.isFinite(value)?value:NaN;}
function drawExtras(){const options=extraOptions();$('extras').innerHTML=extras.map((x,i)=>`<div class="extra"><label>項目<select data-i="${i}" data-choice><option value="">項目を選択してください</option>${options.map(o=>`<option value="${esc(o.I)}" ${x.choice===String(o.I)?'selected':''}>${esc(o.K?o.K+' / '+o.I:o.I)}</option>`).join('')}<option value="__custom__" ${x.choice==='__custom__'?'selected':''}>自由入力</option></select></label>${x.choice==='__custom__'?`<label>内容（請求書への表記）<input data-i="${i}" data-field="name" value="${esc(x.name)}" placeholder="例：Interne Fortbildung"></label>`:''}<div class="twocol"><label>数量<input data-i="${i}" data-field="qty" type="number" min="0" step="0.01" value="${Number.isFinite(x.qty)?x.qty:''}"></label><label>単価（€）<input data-i="${i}" data-field="unit" type="number" min="0" step="0.01" value="${Number.isFinite(x.unit)?x.unit:''}" placeholder="単価を入力"></label></div><button class="remove" data-remove="${i}">この明細を削除</button></div>`).join('');$('extras').querySelectorAll('select').forEach(el=>el.onchange=()=>{const x=extras[Number(el.dataset.i)],option=options.find(o=>String(o.I)===el.value);x.choice=el.value;x.name=option?String(option.I):'';x.unit=option?extraRate(option):NaN;drawExtras();changed();});$('extras').querySelectorAll('input').forEach(el=>el.oninput=()=>{extras[Number(el.dataset.i)][el.dataset.field]=el.dataset.field==='name'?el.value:el.value===''?NaN:Number(el.value);changed();});$('extras').querySelectorAll('button').forEach(el=>el.onclick=()=>{extras.splice(Number(el.dataset.remove),1);drawExtras();changed();});}
$('add').onclick=()=>{extras.push({choice:'',name:'',qty:1,unit:NaN});drawExtras();changed();};
function lines(){return [...groups.filter(g=>g.enabled),...extras.map(x=>({...x,amount:Math.round(x.qty*x.unit*100)/100,dates:[]}))];}
function canPrint(){const t=teacher();return valid&&t&&t.G&&$('date').value&&$('number').value.trim()&&lines().length&&lines().every(l=>String(l.name).trim()&&Number.isFinite(l.qty)&&l.qty>0&&Number.isFinite(l.amount)&&l.amount>=0)&&$('confirmed').checked;}
function render(){if(!valid)return;const t=teacher(),list=lines(),total=list.reduce((a,l)=>a+(Number.isFinite(l.amount)?Math.round(l.amount*100):0),0)/100;const date=$('date').value?new Date($('date').value+'T12:00:00').toLocaleDateString('de-DE'):'';const month=new Date($('month').value+'-01T12:00:00').toLocaleDateString('de-DE',{month:'long',year:'numeric'});$('empty').style.display='none';$('invoice').hidden=false;$('invoice').innerHTML=`<div class="sender"><strong>Rechnung von:</strong><br>${esc(t.C)} ${esc(t.B)}<br>${esc(t.D)}<br>${esc(t.E)}<br><br>Datum: ${esc(date)}</div><div class="recipient">Japanische Schule Köln e.V.<br>Nürnberger Str. 10, 51103 Köln</div><h1 class="invoice-title">Rechnung</h1><div class="meta"><span>Für ${esc(month)}</span><span>Rechnungsnummer: ${esc($('number').value)}</span></div><table class="bill"><thead><tr><th>Fach / Information</th><th class="num">Anzahl</th><th class="num">Einzelpreis</th><th class="num">Summe</th></tr></thead><tbody>${list.map(l=>`<tr><td>${esc(l.name)}${l.dates.length?`<span class="detail">${esc(l.dates.join(', '))}</span>`:''}${l.name==='Fahrgeld'?`<span class="detail">${esc(t.J)}</span>`:''}</td><td class="num">${Number.isFinite(l.qty)?num(l.qty):'–'}</td><td class="num">${Number.isFinite(l.unit)?money(l.unit):'–'}</td><td class="num">${Number.isFinite(l.amount)?money(l.amount):'–'}</td></tr>`).join('')}</tbody></table><div class="total"><span>Rechnungsbetrag</span><span>${money(total)}</span></div><p>Bitte überweisen Sie den Betrag auf das unten genannte Konto.</p><p>Mit freundlichen Grüßen<br>${esc(t.C)} ${esc(t.B)}</p><div class="bank"><dl><dt>Kontoinhaber</dt><dd>${esc(t.F)}</dd><dt>Straße</dt><dd>${esc(t.D)}</dd><dt>Ort</dt><dd>${esc(t.E)}</dd><dt>IBAN</dt><dd>${esc(t.G)||'—'}</dd><dt>BIC</dt><dd>${esc(t.H)||'—'}</dd></dl></div>`;$('print').disabled=!canPrint();}
$('confirmed').onchange=()=>{$('print').disabled=!canPrint();};$('print').onclick=()=>{if(!canPrint())return;document.title=`謝金請求書_${$('month').value}_${teacher().B}`;window.print();};
