const decoder=new TextDecoder();
export async function unzip(buffer){const bytes=new Uint8Array(buffer),v=new DataView(buffer);let end=bytes.length-22;while(end>=Math.max(0,bytes.length-65557)&&v.getUint32(end,true)!==0x06054b50)end--;if(end<0)throw Error('Excelファイルを読み込めません。');let pos=v.getUint32(end+16,true);const entries=new Map();for(let i=0;i<v.getUint16(end+10,true);i++){if(v.getUint32(pos,true)!==0x02014b50)throw Error('対応していないExcel形式です。');const method=v.getUint16(pos+10,true),size=v.getUint32(pos+20,true),plain=v.getUint32(pos+24,true),len=v.getUint16(pos+28,true),extra=v.getUint16(pos+30,true),comment=v.getUint16(pos+32,true),offset=v.getUint32(pos+42,true),name=decoder.decode(bytes.slice(pos+46,pos+46+len));if(plain>30000000)throw Error('シートが大きすぎます。');entries.set(name,async()=>{const start=offset+30+v.getUint16(offset+26,true)+v.getUint16(offset+28,true);const compressed=bytes.slice(start,start+size);if(method===0)return decoder.decode(compressed);if(method!==8)throw Error('対応していない圧縮形式です。');return await new Response(new Blob([compressed]).stream().pipeThrough(new DecompressionStream('deflate-raw'))).text()});pos+=46+len+extra+comment;}return entries;}
const nodes=(el,name)=>Array.from(el.getElementsByTagNameNS('*',name));
const xml=text=>{const d=new DOMParser().parseFromString(text,'application/xml');if(nodes(d,'parsererror').length)throw Error('Excelのデータが破損しています。');return d};
const rich=el=>nodes(el,'t').filter(x=>x.parentNode?.localName!=='rPh').map(x=>x.textContent).join('');
export async function readWorkbook(buffer){const zip=await unzip(buffer);const get=async name=>{if(!zip.has(name))throw Error('必要なシートがありません。');return xml(await zip.get(name)())};const shared=zip.has('xl/sharedStrings.xml')?nodes(await get('xl/sharedStrings.xml'),'si').map(rich):[];const book=await get('xl/workbook.xml');if(nodes(book,'workbookPr')[0]?.getAttribute('date1904')==='1')throw Error('1904年基準の日付形式には対応していません。');const rels=new Map(nodes(await get('xl/_rels/workbook.xml.rels'),'Relationship').map(r=>[r.getAttribute('Id'),r.getAttribute('Target')]));const result={};for(const s of nodes(book,'sheet')){const name=s.getAttribute('name');if(!['出勤簿','講師一覧','index_sheet'].includes(name))continue;let path=rels.get(s.getAttribute('r:id'));path=path.startsWith('/')?path.slice(1):'xl/'+path;const data=await get(path);result[name]=nodes(data,'row').map(r=>{const o={_row:Number(r.getAttribute('r'))};for(const c of nodes(r,'c')){let value=nodes(c,'v')[0]?.textContent??'';if(c.getAttribute('t')==='s')value=shared[Number(value)]??'';else if(c.getAttribute('t')==='inlineStr')value=rich(c);else if(value!==''&&!['str','e'].includes(c.getAttribute('t')))value=Number(value);o[c.getAttribute('r').replace(/\d/g,'')]=value;}return o;});}if(!result['出勤簿']||!result['講師一覧'])throw Error('「出勤簿」と「講師一覧」があるExcelを選択してください。');return result;}
export const dateFromSerial=n=>new Date(Date.UTC(1899,11,30)+Number(n)*86400000);
export function sourceRows(book,teacher,month){return book['出勤簿'].filter(r=>typeof r.A==='number'&&r.F===teacher&&dateFromSerial(r.A).toISOString().slice(0,7)===month);}
export function groupRows(rows){const groups=new Map();for(const r of rows){if(typeof r.L!=='number'||!Number.isFinite(r.L)||typeof r.J!=='number'||!Number.isFinite(r.J)||!r.H)throw Error(`出勤簿 ${r._row}行の金額・数量・カテゴリを確認してください。Excelで再計算して保存後、再度読み込んでください。`);const unit=r.J?r.L/r.J:0;const key=String(r.H)+'|'+unit.toFixed(8);if(!groups.has(key))groups.set(key,{name:r.H,qty:0,amount:0,unit,dates:[],enabled:true});const g=groups.get(key);g.qty+=r.J;g.amount+=Math.round(r.L*100);g.dates.push(dateFromSerial(r.A).toLocaleDateString('de-DE',{timeZone:'UTC'}));}return [...groups.values()].map(g=>({...g,amount:g.amount/100,dates:[...new Set(g.dates)]}));}
